import React,{useState} from 'react';
import { ERAS, REGIONS } from './lib/gameData.js';
import { rollPool, autoGenerateUSA, autoPair, randomVenue, pairingBonus, venueBonus, simulateDay, simulateSingles, getEuropeanMVP, hallSave, hallRead } from './lib/engines.js';
import Reel from './components/Reel.jsx';

function Header(){return <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:22}}><div><div className="gold" style={{fontSize:12,fontWeight:900,letterSpacing:4}}>28-0</div><h1 style={{margin:'4px 0 0',fontSize:28}}>Build Europe. Beat USA.</h1></div><span className="pill">Unofficial Ryder Cup legends simulator</span></div>}
function Shell({children}){return <div className="app"><div className="wrap"><Header/>{children}</div></div>}

function Home({go}){return <Shell><div className="card" style={{padding:28,textAlign:'center'}}><h2 style={{fontSize:44,margin:0}}>Chase the impossible.</h2><p className="muted">Draft a 12-man European Ryder Cup team, pair them up, spin the venue, then try to beat the USA across 28 points.</p><div style={{display:'flex',gap:12,justifyContent:'center',flexWrap:'wrap'}}><button className="btn" onClick={()=>go('easy')}>Easy Mode</button><button className="btn secondary" onClick={()=>go('hard')}>Hard Mode</button><button className="btn secondary" onClick={()=>go('hall')}>Hall of Fame</button></div></div></Shell>}
function Briefing({mode,start,back}){return <Shell><div className="card" style={{padding:24}}><p className="gold" style={{fontWeight:900,letterSpacing:3}}>CAPTAIN'S BRIEFING</p><h2>Build Europe. Beat USA. Chase 28-0.</h2><div className="grid two"><div className="player"><b>{mode==='easy'?'Easy Mode':'Hard Mode'}</b><p className="muted">{mode==='easy'?'Ratings visible, 3 rerolls, suggested pairings and team analysis.':'No ratings, no rerolls, no hints. Pick on Ryder Cup knowledge only.'}</p></div><div className="player"><b>Hidden systems</b><p className="muted">Pairing chemistry, venue fit, home advantage, form and momentum can all swing matches.</p></div></div><ol className="muted"><li>Spin Region and Era together.</li><li>Choose one player from the options.</li><li>Draft 12 players. Max 3 per country.</li><li>Reveal Team USA.</li><li>Set pairings and spin venue.</li><li>Sim Day 1, Day 2, then Singles Day.</li></ol><button className="btn" onClick={start}>Start Draft</button> <button className="btn secondary" onClick={back}>Back</button></div></Shell>}

function Draft({mode,onDone}){const [team,setTeam]=useState([]); const [used,setUsed]=useState(new Set()); const [roll,setRoll]=useState(null); const [spinning,setSpinning]=useState(false); const [pick,setPick]=useState(null); const [rerolls,setRerolls]=useState(mode==='easy'?3:0);
 const spin=()=>{setSpinning(true); setPick(null); const res=rollPool(team,mode,used); setRoll(res); setTimeout(()=>setSpinning(false),2100)};
 const confirm=()=>{ if(!pick)return; const next=[...team,pick]; const u=new Set(used); u.add(pick.baseId); setTeam(next); setUsed(u); setPick(null); setRoll(null); if(next.length===12) onDone(next); };
 const reroll=()=>{ if(rerolls>0){setRerolls(rerolls-1); spin();}};
 if(!roll && !spinning) return <Shell><div className="card" style={{padding:24,textAlign:'center'}}><h2>Draft Round {team.length+1}/12</h2><p className="muted">Spin for a Region and Era. Then pick one European player.</p><button className="btn" onClick={spin}>Spin</button><Squad team={team}/></div></Shell>;
 return <Shell><div className="grid two"><div className="card" style={{padding:18}}><h2>Round {team.length+1}/12</h2><div className="reels"><Reel label="Region" items={REGIONS} value={roll?.region||REGIONS[0]} spinning={spinning}/><Reel label="Era" items={ERAS} value={roll?.era||ERAS[0]} color="gold" spinning={spinning}/></div>{!spinning&&<><p className="muted">{roll.message||`${roll.region} | ${roll.era}`}</p>{mode==='easy'&&<button className="btn secondary" disabled={rerolls<=0} onClick={reroll}>Reroll ({rerolls})</button>}</>}</div><div className="card" style={{padding:18}}><h3>Available players</h3>{spinning?<p className="muted">Spinning…</p>:<div className="grid">{roll.choices.map(p=><button key={p.id} className="player" style={{textAlign:'left',borderColor:pick?.id===p.id?'#c9a84c':'rgba(255,255,255,.13)'}} onClick={()=>setPick(p)}><b>{p.name}</b><br/><span className="muted">{p.nationality} · {p.era}</span>{mode==='easy'&&<><br/><span className="gold">OVR {p.overall}</span></>}</button>)}</div>}{pick&&<div style={{marginTop:14}}><button className="btn" onClick={confirm}>Confirm {pick.name}</button> <button className="btn secondary" onClick={()=>setPick(null)}>X</button></div>}</div></div><Squad team={team}/></Shell>
}
function Squad({team}){return <div className="card" style={{padding:16,marginTop:18}}><b>Squad {team.length}/12</b><div className="grid three" style={{marginTop:10}}>{Array.from({length:12}).map((_,i)=><div className="player" key={i}>{i+1}. {team[i]?.name||'—'}</div>)}</div></div>}

function Opponent({team,onDone}){const [usa,setUsa]=useState(null); const gen=()=>setUsa(autoGenerateUSA()); return <Shell><div className="card" style={{padding:24,textAlign:'center'}}><h2>Team Europe complete</h2><p className="muted">Now Team USA is generated from Ryder Cup legends.</p>{!usa?<button className="btn" onClick={gen}>Reveal Team USA</button>:<><div className="grid three">{usa.map((p,i)=><div className="player" key={p.id}>{i+1}. {p.name}<br/><span className="muted">{p.era}</span></div>)}</div><button className="btn" style={{marginTop:16}} onClick={()=>onDone(usa)}>Set Pairings</button></>}</div></Shell>}

function Pairings({team,onDone}){const [pairs,setPairs]=useState([]); const [slot,setSlot]=useState(null); const paired=new Set(pairs.flat().map(p=>p.baseId)); const free=team.filter(p=>!paired.has(p.baseId)); const click=p=>{if(slot){ if(slot.baseId!==p.baseId) setPairs([...pairs,[slot,p]]); setSlot(null)}else setSlot(p)}; return <Shell><div className="grid two"><div className="card" style={{padding:20}}><h2>Set Pairings</h2><p className="muted">Pair players for foursomes/fourballs. Bonuses stay vague until the result.</p><button className="btn secondary" onClick={()=>setPairs(autoPair(team))}>Auto Pair Team</button><div className="grid" style={{marginTop:12}}>{free.map(p=><button className="player" onClick={()=>click(p)} key={p.id} style={{textAlign:'left',borderColor:slot?.baseId===p.baseId?'#c9a84c':'rgba(255,255,255,.13)'}}>{p.name}<br/><span className="muted">{p.nationality}</span></button>)}</div></div><div className="card" style={{padding:20}}><h3>Pairings {pairs.length}/6</h3>{pairs.map((pr,i)=><div className="player" key={i}><b>{i+1}. {pr[0].name} / {pr[1].name}</b> <button className="btn secondary" style={{padding:6,float:'right'}} onClick={()=>setPairs(pairs.filter((_,x)=>x!==i))}>X</button></div>)}<button className="btn" disabled={pairs.length<4} onClick={()=>onDone(pairs)} style={{marginTop:14}}>Confirm Pairings</button></div></div></Shell>}

function Venue({team,pairs,onDone}){const [venue,setVenue]=useState(null); const spin=()=>setVenue(randomVenue()); if(!venue)return <Shell><div className="card" style={{padding:24,textAlign:'center'}}><h2>Spin the Venue</h2><p className="muted">Venue can affect home advantage, course fit and hidden boosts.</p><button className="btn" onClick={spin}>Spin Venue</button></div></Shell>; const pb=pairingBonus(pairs); const vb=venueBonus(team,venue,'Europe'); return <Shell><div className="card" style={{padding:24}}><p className="gold">Venue confirmed</p><h2>{venue.name}</h2><p className="muted">{venue.country} · {venue.desc}</p><p><b>Course rewards:</b> {venue.attrs.join(', ')}</p><div className="player"><b>Bonus Summary</b><p>{pb+vb.total===0?'No bonuses found.':`Pairing Bonuses: +${pb} · Venue Bonuses: +${vb.venue} · Home Advantage: +${vb.homeAdvantage} · Home Nation Bonuses: +${vb.homeNation} · Total: +${pb+vb.total}`}</p></div><button className="btn" onClick={()=>onDone(venue)}>Begin Ryder Cup</button></div></Shell>}

function Simulate({team,usa,pairs,venue,onDone}){const [stage,setStage]=useState(0); const [score,setScore]=useState({eu:0,us:0}); const [sessions,setSessions]=useState([]); const [pts,setPts]=useState({}); const runDay=(n)=>{const res=n<3?simulateDay(team,usa,pairs,venue,n):simulateSingles(team,usa,venue); setScore(s=>({eu:s.eu+res.eu,us:s.us+res.us})); setSessions(ss=>[...ss,...res.sessions]); setPts(pt=>{const next={...pt}; Object.entries(res.playerPts).forEach(([k,v])=>next[k]=(next[k]||0)+v); return next}); setStage(stage+1)}; if(stage>=3)return <Results team={team} usa={usa} score={score} sessions={sessions} pts={pts} venue={venue} onDone={onDone}/>; const label=stage===0?'Simulate Day 1':stage===1?'Simulate Day 2':'Simulate Singles Day'; return <Shell><Score score={score}/><DayBoard sessions={sessions}/><div style={{textAlign:'center'}}><button className="btn" onClick={()=>runDay(stage+1)}>{label}</button></div></Shell>}
function Score({score}){return <div className="card" style={{padding:22,textAlign:'center',marginBottom:18}}><div className="grid two"><div><p className="blue">EUROPE</p><div className="score">{score.eu}</div></div><div><p className="red">USA</p><div className="score">{score.us}</div></div></div><p className="muted">Target: 14.5 · 28 points available</p></div>}
function DayBoard({sessions}){if(!sessions.length)return <p className="muted" style={{textAlign:'center'}}>No sessions played yet.</p>; return <div className="grid">{sessions.map((s,i)=><div className="card" style={{padding:16}} key={i}><h3>{s.name}: Europe {s.eu} - {s.us} USA</h3><table className="table"><tbody>{s.matches.map((m,j)=><tr key={j}><td>{m.euNames}</td><td><b>{m.score}</b></td><td>{m.usNames}</td></tr>)}</tbody></table></div>)}</div>}

function Results({team,score,sessions,pts,venue,onDone}){const mvp=getEuropeanMVP(team,pts); hallSave({score, mvp:mvp?.name, venue:venue.name}); return <Shell><div className="card" style={{padding:28,textAlign:'center'}}><p className="gold">FINAL RESULT</p><h2 style={{fontSize:42}}>Europe {score.eu} - {score.us} USA</h2><p className="muted">{score.eu>score.us?'Europe wins.':'USA wins.'}</p><div className="player"><b>European MVP</b><p>{mvp?.name} · {pts[mvp?.baseId]||0} points</p></div><button className="btn" onClick={onDone}>Play Again</button></div><DayBoard sessions={sessions}/></Shell>}
function Hall({back}){const h=hallRead();return <Shell><div className="card" style={{padding:24}}><h2>Hall of Fame</h2>{!h.length?<p className="muted">No completed Ryder Cups yet.</p>:h.map((x,i)=><div className="player" key={i}>Europe {x.score.eu} - {x.score.us} USA · MVP: {x.mvp} · {x.venue}</div>)}<button className="btn secondary" onClick={back}>Back</button></div></Shell>}

export default function App(){const [page,setPage]=useState('home');const [mode,setMode]=useState('easy');const [team,setTeam]=useState([]);const [usa,setUsa]=useState([]);const [pairs,setPairs]=useState([]);const [venue,setVenue]=useState(null); const reset=()=>{setTeam([]);setUsa([]);setPairs([]);setVenue(null);setPage('home')};
 if(page==='home')return <Home go={p=>{if(p==='hall')setPage('hall');else{setMode(p);setPage('briefing')}}}/>;
 if(page==='hall')return <Hall back={()=>setPage('home')}/>;
 if(page==='briefing')return <Briefing mode={mode} start={()=>setPage('draft')} back={()=>setPage('home')}/>;
 if(page==='draft')return <Draft mode={mode} onDone={t=>{setTeam(t);setPage('opponent')}}/>;
 if(page==='opponent')return <Opponent team={team} onDone={u=>{setUsa(u);setPage('pairings')}}/>;
 if(page==='pairings')return <Pairings team={team} onDone={p=>{setPairs(p);setPage('venue')}}/>;
 if(page==='venue')return <Venue team={team} pairs={pairs} onDone={v=>{setVenue(v);setPage('sim')}}/>;
 if(page==='sim')return <Simulate team={team} usa={usa} pairs={pairs} venue={venue} onDone={reset}/>;
 return null;
}
